# Generated by Django 6.1.1 on 2026-09-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField()),
                ('tipo_entrega', models.CharField(blank=True, max_length=50)),
                ('responsable_entrega', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_abono', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'negocio',
            },
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'preparacion',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_label', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('dimensiones', models.CharField(blank=True, max_length=150)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('precio_arriendo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('unidad_precio', models.CharField(blank=True, max_length=100)),
                ('imagen', models.CharField(blank=True, max_length=255)),
                ('imagenes', models.JSONField(blank=True, default=list)),
                ('stock_total', models.PositiveIntegerField(default=0)),
                ('stock_trabajable', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='Inventario.categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='Inventario.negocio')),
            ],
            options={
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_despacho', to='Inventario.articulo')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.despacho')),
            ],
            options={
                'db_table': 'detalle_despacho',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_buena', models.PositiveIntegerField(default=0)),
                ('cantidad_danada', models.PositiveIntegerField(default=0)),
                ('cantidad_pendiente', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='Inventario.articulo')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.devolucion')),
            ],
            options={
                'db_table': 'detalle_devolucion',
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('valor_reposicion', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='Inventario.articulo')),
                ('detalle_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='Inventario.detalledevolucion')),
            ],
            options={
                'db_table': 'merma',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Inventario.negocio')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='Inventario.negocio'),
        ),
        migrations.CreateModel(
            name='DetallePreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_preparada', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_preparacion', to='Inventario.articulo')),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.preparacion')),
            ],
            options={
                'db_table': 'detalle_preparacion',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(max_length=30)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('direccion_evento', models.CharField(blank=True, max_length=255)),
                ('comuna_evento', models.CharField(blank=True, max_length=100)),
                ('cantidad_personas', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('abono', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('garantia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='Inventario.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='Inventario.negocio')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.AddField(
            model_name='preparacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='Inventario.servicio'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='Inventario.servicio'),
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_servicio', to='Inventario.articulo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.servicio')),
            ],
            options={
                'db_table': 'detalle_servicio',
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='Inventario.servicio'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Inventario.negocio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Inventario.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='preparacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparaciones', to='Inventario.usuario'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField(blank=True, null=True)),
                ('stock_nuevo', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='Inventario.articulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='Inventario.usuario')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='Inventario.usuario'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='Inventario.usuario'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(condition=models.Q(('stock_trabajable__lte', models.F('stock_total'))), name='stock_trabajable_no_supera_total'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__isnull', True), ('fecha_termino__isnull', True), ('fecha_termino__gte', models.F('fecha_inicio')), _connector='OR'), name='fecha_termino_mayor_inicio'),
        ),
    ]
